In [2]:
import pandas as pd

In [3]:
#read csv files
df1 = pd.read_csv('202205-citibike-tripdata.csv', low_memory=False)
df2 = pd.read_csv('202305-citibike-tripdata.csv', low_memory=False)
df3 = pd.read_csv('JC-202205-citibike-tripdata.csv', low_memory=False)
df4 = pd.read_csv('JC-202305-citibike-tripdata.csv', low_memory=False)

In [4]:
#drop null values
df1.dropna(how='all')
df2.dropna(how='all')
df3.dropna(how='all')
df4.dropna(how='all')

,ride_id,rideable_type,started_at,time_started,ended_at,time_ended,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,BC145343639B5E5B,classic_bike,5/31/2023 12:27,12:27:28 PM,5/31/2023 12:38,12:38:36 PM,Pershing Field,JC024,Newport PATH,JC066,40.742675,-74.051806,40.727224,-74.033759,member
1,A0CE41F47514FF5C,classic_bike,5/1/2023 18:12,6:12:37 PM,5/1/2023 18:29,6:29:03 PM,Pershing Field,JC024,Baldwin at Montgomery,JC020,40.742638,-74.051815,40.723659,-74.064194,casual
2,D588077E3D7E2AFD,electric_bike,5/28/2023 17:37,5:37:58 PM,5/28/2023 18:39,6:39:39 PM,Pershing Field,JC024,Pershing Field,JC024,40.742677,-74.051789,40.742677,-74.051789,casual
3,89AC48A5584B2DB4,classic_bike,5/27/2023 21:01,9:01:37 PM,5/27/2023 21:13,9:13:16 PM,Pershing Field,JC024,Manila & 1st,JC082,40.742677,-74.051789,40.721651,-74.042884,member
4,709E0B11AB4A0E6C,classic_bike,5/22/2023 12:38,12:38:54 PM,5/22/2023 13:02,1:02:13 PM,Pershing Field,JC024,Jersey & 3rd,JC074,40.742677,-74.051789,40.723332,-74.045953,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95997,9549398286BB59B5,docked_bike,5/27/2023 13:24,1:24:51 PM,5/27/2023 13:51,1:51:18 PM,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,Newport Pkwy,JC008,40.736982,-74.027781,40.728745,-74.032108,casual
95998,AB0790683044D89E,classic_bike,5/18/2023 17:12,5:12:07 PM,5/18/2023 17:25,5:25:02 PM,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,Warren St,JC006,40.736982,-74.027781,40.721124,-74.038051,member
95999,68226FA538A405CA,classic_bike,5/5/2023 18:44,6:44:57 PM,5/5/2023 18:56,6:56:15 PM,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,Warren St,JC006,40.736982,-74.027781,40.721124,-74.038051,member
96000,CABAC21C0F0140A5,classic_bike,5/16/2023 11:56,11:56:11 AM,5/16/2023 12:04,12:04:04 PM,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member
96001,4AABD797EF6F7BB2,classic_bike,5/30/2023 11:04,11:04:46 AM,5/30/2023 11:13,11:13:54 AM,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,Warren St,JC006,40.736982,-74.027781,40.721124,-74.038051,member

In [5]:
#concat nyc data into one dataframe
nyc = [df1, df2]
nycdf = pd.concat(nyc)

In [6]:
#concat JC data into one dataframe
jc = [df3, df4]
jcdf = pd.concat(jc)

In [7]:
#jcdf.head()

In [8]:
# save new csv files
#jcdf.to_csv('jc-citibike.csv', index=False)
#nycdf.to_csv('nyc-citibike.csv', index=False)

In [9]:
# check column types
#nycdf.dtypes
jcdf.dtypes

ride_id                object
rideable_type          object
started_at             object
time_started           object
ended_at               object
time_ended             object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [10]:
# change time_started/ended columns to datetime
nycdf['time_started'] = pd.to_datetime(nycdf['time_started'])
nycdf['time_ended'] = pd.to_datetime(nycdf['time_ended'])
jcdf['time_started'] = pd.to_datetime(jcdf['time_started'])
jcdf['time_ended'] = pd.to_datetime(jcdf['time_ended'])

In [11]:
# concat two files together
dflist = [jcdf, nycdf]
citibikedf = pd.concat(dflist)

In [12]:
# add duration column with minutes biked
citibikedf['Duration'] = ((citibikedf.time_ended) - (citibikedf.time_started))/pd.Timedelta(minutes=1)

In [13]:
citibikedf.head()

,ride_id,rideable_type,started_at,time_started,ended_at,time_ended,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,Duration
0,FC9EB68D6501F079,electric_bike,5/15/2022 14:02,2023-07-27 14:02:06,5/15/2022 14:05,2023-07-27 14:05:44,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Hudson St & 4 St,HB607,40.735938,-74.030305,40.740973,-74.028603,member,3.633333
1,932A2D5E45ACED5B,electric_bike,5/13/2022 15:30,2023-07-27 15:30:14,5/13/2022 15:33,2023-07-27 15:33:03,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Hudson St & 4 St,HB607,40.735938,-74.030305,40.740973,-74.028603,casual,2.816667
2,8C0CD371C7A5795C,electric_bike,5/31/2022 20:41,2023-07-27 20:41:39,5/31/2022 22:04,2023-07-27 22:04:47,Hoboken Terminal - Hudson St & Hudson Pl,HB101,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,40.735938,-74.030305,40.736982,-74.027781,casual,83.133333
3,25BC1B079FBC71B9,classic_bike,5/29/2022 17:24,2023-07-27 17:24:23,5/30/2022 18:24,2023-07-27 18:24:16,Hoboken Terminal - Hudson St & Hudson Pl,HB101,NaN,NaN,40.735938,-74.030305,NaN,NaN,member,59.883333
4,0B0F776B55C85AB8,classic_bike,5/26/2022 16:49,2023-07-27 16:49:12,5/26/2022 16:57,2023-07-27 16:57:01,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Hoboken Ave at Monmouth St,JC105,40.735938,-74.030305,40.735208,-74.046964,member,7.816667

In [14]:
citibikedf.to_csv('combined_citibike.csv', index=False)